--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Contacts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Contacts" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Email" text NOT NULL
);


ALTER TABLE public."Contacts" OWNER TO postgres;

--
-- Name: Contacts_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Contacts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Contacts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Contacts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Contacts" ("Id", "Name", "Email") FROM stdin;
3	Леонид Лобанов	leonid.lobanov@example.com
4	Маргарита Ильина	margarita.ilina@example.com
8	Александра Бобылева	aleksandra.bobyleva@example.com
9	Юлия Мясникова	yuliya.myasnikova@example.com
10	Андрей Суворов	andrey.suvorov@example.com
11	Валерия Белова	valeriya.belova@example.com
12	Лаврентий Субботин	lavrentiy.subbotin@example.com
13	Константин Щукин	konstantin.shchukin@example.com
14	Константин Егоров	konstantin.egorov@example.com
15	Алина Михайлова	alina.mikhaylova@example.com
16	Артём Пестов	artyom.pestov@example.com
17	Ирина Терентьева	irina.terenteva@example.com
18	Геннадий Борисов	gennadiy.borisov@example.com
19	Ольга Павлова	olga.pavlova@example.com
20	Матвей Комаров	matvey.komarov@example.com
21	Артём Киселев	artyom.kiselev@example.com
22	Лариса Фролова	larisa.frolova@example.com
23	Максим Назаров	maksim.nazarov@example.com
24	Макар Панфилов	makar.panfilov@example.com
25	Мария Власова	mariya.vlasova@example.com
26	Лариса Щербакова	larisa.shcherbakova@example.com
27	Евгений Савин	evgeniy.savin@example.com
28	Валерий Кулагин	valeriy.kulagin@example.com
29	Маргарита Гаврилова	margarita.gavrilova@example.com
30	Юрий Лихачев	yuriy.likhachev@example.com
31	Георгий Комиссаров	georgiy.komissarov@example.com
32	Любовь Рябова	lyubov.ryabova@example.com
33	Регина Маслова	regina.maslova@example.com
34	Екатерина Дементьева	ekaterina.dementeva@example.com
35	Арина Пахомова	arina.pakhomova@example.com
36	Игорь Попов	igor.popov@example.com
37	Эдуард Новиков	eduard.novikov@example.com
38	Оксана Комарова	oksana.komarova@example.com
39	Елизавета Горшкова	elizaveta.gorshkova@example.com
40	Валентина Русакова	valentina.rusakova@example.com
41	Елена Сергеева	elena.sergeeva@example.com
42	Алевтина Селиверстова	alevtina.seliverstova@example.com
43	Варвара Ларионова	varvara.larionova@example.com
44	Иван Мухин	ivan.mukhin@example.com
45	Александр Муравьев	aleksandr.muravev@example.com
46	Николай Смирнов	nikolay.smirnov@example.com
47	Анастасия Калинина	anastasiya.kalinina@example.com
48	Лидия Ситникова	lidiya.sitnikova@example.com
49	Антон Захаров	anton.zakharov@example.com
50	Ирина Молчанова	irina.molchanova@example.com
51	Виктория Никонова	viktoriya.nikonova@example.com
52	Жанна Баранова	zhanna.baranova@example.com
53	Григорий Исаев	grigoriy.isaev@example.com
54	Надежда Голубева	nadezhda.golubeva@example.com
55	Галина Морозова	galina.morozova@example.com
56	Ульяна Веселова	ulyana.veselova@example.com
57	Таисия Фомина	taisiya.fomina@example.com
58	Герман Сафонов	german.safonov@example.com
59	Зинаида Федотова	zinaida.fedotova@example.com
60	Фёдор Савельев	fyodor.savelev@example.com
61	Александр Савин	aleksandr.savin@example.com
62	Григорий Авдеев	grigoriy.avdeev@example.com
63	Дарья Яковлева	darya.yakovleva@example.com
64	Арина Филатова	arina.filatova@example.com
65	Даниил Белов	daniil.belov@example.com
66	Егор Ситников	egor.sitnikov@example.com
67	Денис Мухин	denis.mukhin@example.com
68	Владимир Дьячков	vladimir.dyachkov@example.com
69	Георгий Тимофеев	georgiy.timofeev@example.com
70	Марина Горбачева	marina.gorbacheva@example.com
71	Анатолий Тетерин	anatoliy.teterin@example.com
72	Кира Щукина	kira.shchukina@example.com
73	Валентин Федосеев	valentin.fedoseev@example.com
74	Аркадий Русаков	arkadiy.rusakov@example.com
75	Алла Попова	alla.popova@example.com
76	Геннадий Комаров	gennadiy.komarov@example.com
77	Валерий Копылов	valeriy.kopylov@example.com
78	Лука Ершов	luka.ershov@example.com
79	Анна Дьячкова	anna.dyachkova@example.com
80	Илья Дорофеев	ilya.dorofeev@example.com
81	Егор Зыков	egor.zykov@example.com
82	Игорь Орехов	igor.orekhov@example.com
83	Лариса Кириллова	larisa.kirillova@example.com
84	Анатолий Гусев	anatoliy.gusev@example.com
85	Вячеслав Никифоров	vyacheslav.nikiforov@example.com
86	Степан Калашников	stepan.kalashnikov@example.com
87	Людмила Фролова	lyudmila.frolova@example.com
1	string	string
6	Илья Беспалов 123131	ilya.bespalov@example.com
5	Ярослав Доронин 1	yaroslav.doronin@example.com
88	Алёна Исаева	alyona.isaeva@example.com
89	Ксения Селиверстова	kseniya.seliverstova@example.com
90	Маргарита Никонова	margarita.nikonova@example.com
91	Михаил Куликов	mikhail.kulikov@example.com
92	Виктория Тихонова	viktoriya.tikhonova@example.com
93	Ирина Ефимова	irina.efimova@example.com
94	Лука Савин	luka.savin@example.com
95	Ангелина Пахомова	angelina.pakhomova@example.com
96	Владимир Ермаков	vladimir.ermakov@example.com
97	Вадим Михеев	vadim.mikheev@example.com
98	Елена Устинова	elena.ustinova@example.com
99	Римма Мухина	rimma.mukhina@example.com
100	Дарья Носкова	darya.noskova@example.com
101	Леонид Якушев	leonid.yakushev@example.com
102	Денис Емельянов	denis.emelyanov@example.com
103	Алла Ковалева	alla.kovaleva@example.com
104	Георгий Дорофеев	georgiy.dorofeev@example.com
105	Леонид Савельев	leonid.savelev@example.com
106	Алексей Крылов	aleksey.krylov@example.com
107	Станислав Русаков	stanislav.rusakov@example.com
108	Тамара Григорьева	tamara.grigoreva@example.com
109	Алина Павлова	alina.pavlova@example.com
110	Римма Давыдова	rimma.davydova@example.com
111	Фёдор Ковалев	fyodor.kovalev@example.com
112	Вячеслав Степанов	vyacheslav.stepanov@example.com
113	Василий Орлов	vasiliy.orlov@example.com
114	Клавдия Громова	klavdiya.gromova@example.com
115	Виталий Назаров	vitaliy.nazarov@example.com
116	Константин Поляков	konstantin.polyakov@example.com
117	Нина Михеева	nina.mikheeva@example.com
118	Дарья Кудряшова	darya.kudryashova@example.com
119	Арина Копылова	arina.kopylova@example.com
120	Андрей Зуев	andrey.zuev@example.com
121	Ярослав Копылов	yaroslav.kopylov@example.com
122	Екатерина Моисеева	ekaterina.moiseeva@example.com
123	Михаил Гусев	mikhail.gusev@example.com
124	Регина Кудрявцева	regina.kudryavtseva@example.com
125	Евгений Никитин	evgeniy.nikitin@example.com
126	Марина Зыкова	marina.zykova@example.com
127	Григорий Суворов	grigoriy.suvorov@example.com
128	Лука Агафонов	luka.agafonov@example.com
129	Ярослав Соколов	yaroslav.sokolov@example.com
130	Евгений Рыбаков	evgeniy.rybakov@example.com
131	Надежда Полякова	nadezhda.polyakova@example.com
132	Мария Уварова	mariya.uvarova@example.com
133	Владислав Белозеров	vladislav.belozerov@example.com
134	Сергей Марков	sergey.markov@example.com
135	Регина Мишина	regina.mishina@example.com
136	Василиса Никифорова	vasilisa.nikiforova@example.com
137	Ксения Вишнякова	kseniya.vishnyakova@example.com
138	Людмила Большакова	lyudmila.bolshakova@example.com
139	Ульяна Кондратьева	ulyana.kondrateva@example.com
140	Ольга Родионова	olga.rodionova@example.com
141	Маргарита Корнилова	margarita.kornilova@example.com
142	Вячеслав Воробьев	vyacheslav.vorobev@example.com
143	Раиса Костина	raisa.kostina@example.com
144	София Дьячкова	sofiya.dyachkova@example.com
145	Эдуард Пестов	eduard.pestov@example.com
146	Наталья Ширяева	natalya.shiryaeva@example.com
147	Илья Рожков	ilya.rozhkov@example.com
148	Анжела Пономарева	anzhela.ponomareva@example.com
149	Николай Горбунов	nikolay.gorbunov@example.com
150	Николай Зуев	nikolay.zuev@example.com
151	Анна Карпова	anna.karpova@example.com
152	Жанна Крюкова	zhanna.kryukova@example.com
153	Алёна Киселева	alyona.kiseleva@example.com
154	Антон Игнатов	anton.ignatov@example.com
155	Андрей Петров	andrey.petrov@example.com
156	Ксения Гришина	kseniya.grishina@example.com
157	Анастасия Макарова	anastasiya.makarova@example.com
158	Никита Смирнов	nikita.smirnov@example.com
159	Аркадий Смирнов	arkadiy.smirnov@example.com
160	Александр Поляков	aleksandr.polyakov@example.com
161	Валерия Хохлова	valeriya.khokhlova@example.com
162	Альберт Муравьев	albert.muravev@example.com
163	Дарья Михайлова	darya.mikhaylova@example.com
164	Юрий Фокин	yuriy.fokin@example.com
165	Игнатий Якушев	ignatiy.yakushev@example.com
166	Степан Калинин	stepan.kalinin@example.com
167	Антон Филатов	anton.filatov@example.com
168	Эдуард Лебедев	eduard.lebedev@example.com
169	Андрей Борисов	andrey.borisov@example.com
170	Роман Павлов	roman.pavlov@example.com
171	Ксения Осипова	kseniya.osipova@example.com
172	Валерия Комарова	valeriya.komarova@example.com
173	Вера Пономарева	vera.ponomareva@example.com
174	Алина Воронова	alina.voronova@example.com
175	Тамара Селиверстова	tamara.seliverstova@example.com
176	Дмитрий Родионов	dmitriy.rodionov@example.com
177	Антон Юдин	anton.yudin@example.com
178	Игнатий Логинов	ignatiy.loginov@example.com
179	Елизавета Ширяева	elizaveta.shiryaeva@example.com
180	Ольга Ермакова	olga.ermakova@example.com
181	Алина Юдина	alina.yudina@example.com
182	Анжелика Капустина	anzhelika.kapustina@example.com
183	Жанна Устинова	zhanna.ustinova@example.com
184	Лука Гусев	luka.gusev@example.com
185	Сергей Лапин	sergey.lapin@example.com
186	Виктория Горшкова	viktoriya.gorshkova@example.com
187	Артём Носков	artyom.noskov@example.com
188	Аркадий Герасимов	arkadiy.gerasimov@example.com
189	Игнатий Зуев	ignatiy.zuev@example.com
190	Ксения Родионова	kseniya.rodionova@example.com
191	Эдуард Доронин	eduard.doronin@example.com
192	Тамара Юдина	tamara.yudina@example.com
193	Антонида Артемьева	antonida.artemeva@example.com
194	Владислав Лукин	vladislav.lukin@example.com
195	Арсений Кудряшов	arseniy.kudryashov@example.com
197	Анфиса Дьячкова	anfisa.dyachkova@example.com
198	София Веселова	sofiya.veselova@example.com
199	Георгий Сидоров	georgiy.sidorov@example.com
200	Олег Шарапов	oleg.sharapov@example.com
196	Семён Исаев 2131	semyon.isaev@example.com
201	new name	new email
202	qweqeq	eqweqe
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20251104075955_InitialMigration	9.0.10
20251107104347_InitialCreate	9.0.10
20251108094457_InitialCreate	9.0.10
\.


--
-- Name: Contacts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Contacts_Id_seq"', 203, true);


--
-- Name: Contacts PK_Contacts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Contacts"
    ADD CONSTRAINT "PK_Contacts" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- PostgreSQL database dump complete
--

